### ISSUE TITLE
implementation of stack data structures in any language.

### ISSUE THREAD

**Issue by Astrogeek77** [Astrogeek77/Hacktoberfest_2021#11]
Reply here and tell me which data structure you want to implement, i will assign it to you.

always check for previously assigned tasks before request for a new one.

**Comment by ayush7801** [comment]
Hey there, i think i can implement stack both array implementation and linked list implementation. I want you to assign this task to me

**Comment by ayush7801** [comment]
Thanks i will be on it

**Comment by nishantkumar1308** [comment]
Assign it to me

**Comment by Astrogeek77** [comment]
Task is already assigned and done, i am making more issues soon.
