### ISSUE TITLE
Implementation of Queue data structure in any language.

### ISSUE THREAD

**Issue by Astrogeek77** [Astrogeek77/Hacktoberfest_2021#15]
Reply here and tell me how you want to implement, i will assign the task to you.

always check for previously assigned tasks before request for a new one.

**Comment by nishantkumar1308** [comment]
Please assign me in C++ . I will do it

**Comment by jasmine1601** [comment]
@Astrogeek77 Can I solve this in Java?

**Comment by chickenCHRISpy** [comment]
Heyy there interested to do this task in python. Can you please assign it? Thanks.

**Comment by Astrogeek77** [comment]
Okay @jasmine1601 can implement in java and @chickenCHRISpy can do it in python.

**Comment by sejalsingh417** [comment]
Please assign me in C++.

**Comment by harshitsuthar77731** [comment]
please assign me in javascript

**Comment by Astrogeek77** [comment]
@sejalsingh417 task is already done in C++, you can choose another language . @harshitsuthar77731 you can go ahead.
