### ISSUE TITLE
implementation of Linked List Data Structure in different languages.

### ISSUE THREAD

**Issue by Astrogeek77** [Astrogeek77/Hacktoberfest_2021#22]
Reply here to get assigned the language you want to implement in and i will assign to you.

**Comment by 96RadhikaJadhav** [comment]
Hi @Astrogeek77  I will do it in python. Can you please assign this issue to me?

**Comment by Astrogeek77** [comment]
ok @96RadhikaJadhav Go ahead!

**Comment by 96RadhikaJadhav** [comment]
Also if you add other issues like implementing all other DSA programs with some other python programs also, I would like to contribute to it. Please open an issue for the same and assign to me or let me know if I should open.

**Comment by Astrogeek77** [comment]
Yes you can open issues as well.

**Comment by sejalsingh417** [comment]
I will do it in c++, please assign it to me

**Comment by Astrogeek77** [comment]
okay,  @sejalsingh417  go ahead.

**Comment by harshitsuthar77731** [comment]
assign me in js

**Comment by Astrogeek77** [comment]
okay

**Comment by satvik07-ynk** [comment]
assign me in c language

**Comment by Astrogeek77** [comment]
okay, @satvik07-ynk go ahead!

**Comment by harshitsuthar77731** [comment]
assign me in java

**Comment by Astrogeek77** [comment]
okay go ahead 👍

**Comment by pcpriyankapc** [comment]
Please assign me I will do it in Java

**Comment by Astrogeek77** [comment]
okay @pcpriyankapc go Ahead! 💯

**Comment by Astrogeek77** [comment]
this task is completed
