### ISSUE TITLE
Tower Of Hanoi Problem in any language using any method.

### ISSUE THREAD

**Issue by Astrogeek77** [Astrogeek77/Hacktoberfest_2021#33]
reply here if you want to get assigned this task, i will reply soon.

**Comment by shreerajbhamare** [comment]
I will do this in **Python** language, please assign it to me

**Comment by harshitsuthar77731** [comment]
assign me in c++

**Comment by Astrogeek77** [comment]
Go Ahead @harshitsuthar77731 and @shreerajbhamare  👍

**Comment by himanshukaushal123** [comment]
Please assign me I will do it in Javascript

**Comment by Astrogeek77** [comment]
okay @himanshukaushal123 Go ahead 👍

**Comment by pcpriyankapc** [comment]
Please assign me this I will do it in Java.

**Comment by Astrogeek77** [comment]
ok @pcpriyankapc go ahead 💯

**Comment by kritikatonk** [comment]
i will do this in c++ please assign it to me.

**Comment by vivekarora-02** [comment]
Hey there, 
I would like to contribute towards this issue. Can ypu please assign me this issue?

ThankYou!

**Comment by Devika0713** [comment]
Hello! I can do this in c as well as c++ Can you please assign this to me?
Thank you.

**Comment by Astrogeek77** [comment]
the task is already done in CPP, JS and Python, Please choose another language. @Devika0713 you can go ahead for c 👍
