### ISSUE TITLE
sorting algorithms in any language

### ISSUE THREAD

**Issue by Astrogeek77** [Astrogeek77/Hacktoberfest_2021#44]
Reply here to get assigned a task.

**Comment by nishantkumar1308** [comment]
please assign it to me i can do it in c++

**Comment by nishantkumar1308** [comment]
I can write all 4-5 sorting alogrithm in c++.

**Comment by Tamoghna2001** [comment]
please assign it to me

**Comment by Astrogeek77** [comment]
ok @nishantkumar1308 go for cpp and @Tamoghna2001 choose another language please

**Comment by himanshukaushal123** [comment]
Please assign to me I can do it in Javascript

**Comment by Astrogeek77** [comment]
okay @himanshukaushal123 Go for it 👍

**Comment by Amritanshu02** [comment]
Hello, I will write the sorting algo in java, could you assign it to me

**Comment by Tamoghna2001** [comment]
i can do it in c++

**Comment by pcpriyankapc** [comment]
Please assign it to me I can write all sorting algorithms in Java.
Thanks

**Comment by Astrogeek77** [comment]
okay guys go ahead. 💯

**Comment by vivekarora-02** [comment]
Hey there,
I would like to contribute towards this issue. Can ypu please assign me this issue?

ThankYou!

**Comment by Astrogeek77** [comment]
this task is already completed. Thank you

**Comment by nishantkumar1308** [comment]
Astrogeek77 Kindly give me hacktoberfest-accepted tag on my pr #61
