### ISSUE TITLE
Fibonaaci series in any language

### ISSUE THREAD

**Issue by Astrogeek77** [Astrogeek77/Hacktoberfest_2021#82]
Reply Here to get assigned this task

**Comment by Astrogeek77** [comment]
okay go ahead 👍

**Comment by yasas2002** [comment]
please assign me

**Comment by Devika0713** [comment]
Hello again! I can contribute a c file for finding the nth Fibonacci series. Can you please assign this to me ?
Thank you

**Comment by codedrian** [comment]
Good day sir. This is my first time participating in Hacktoberfest. Can you assign me to this issue? Thanks

**Comment by Astrogeek77** [comment]
Sure go Ahead 💯

**Comment by abhijeet-crypto** [comment]
@Astrogeek77 i want to work on this issue please assign to me.
